site_name: fk的博客
site_author: fk
site_description: 这是我的个人博客
theme:
  name: readthedocs
nav:
  - 首页: index.md
  - 随笔: 20250904.md
  - 测试: 20250904-1.md
extra_css:
  - css/extra.css

site_url: https://KkaiFang.github.io/my_notes/
