name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main   # 或者 master，看你代码的主分支

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-document-dates
          pip install mkdocs-ai-summary-wcowin -i https://pypi.org/simple

      - name: Build and Deploy
        run: mkdocs gh-deploy --force
